ai:
  # [aliyun|ollama]
  name: aliyun
  ak: sk-xxxxxxxxxxxxxxxxxxx
  # qwen1.5-72b-chat ⭐⭐⭐⭐
  # qwen1.5-14b-chat ⭐⭐⭐
  # qwen1.5-7b-chat ⭐⭐
  # qwen-1.8b-chat ⭐
  # qwen-plus 未知
  # qwen-turbo 未知
  # qwen-max-1201 未知
  # qwen-max-longcontext ⭐⭐⭐⭐
  model: qwen-max-longcontext
git:
  # 不会空则以此username为准，防止误领别人的工作
  # 为空字符串则自动获取
  username:
  repo:
    # [数组]
    # 自动遍历目录下的所有git仓库
    # 可以填项目集中的目录: C:\Web
    # 也可以填具体仓库目录: C:\Web\niubiGame
    - C:\Web
report:
  # 报告模式
  # [normal 详细叙述] [simple 简单概要]
  mode: normal
  # 间隔多少天汇报一次，默认一天报告一次
  # 1=只含今天，2=今天和昨天
  intervalDay: 1
  # 输出模式
  # file 输出文本文件
  # print 打印到终端
  out: file
  # 报告语言 [chs|en]
  lang: chs