# 对于不使用的接口，可以不填
ai:
  aliyun-dashscope:
    model: qwen1.5-72b-chat
    apiKey: sk-xxxxxxxxxxxxxxxxxxx
    baseUrl: https://dashscope.aliyuncs.com
    # 请按当前大模型支持的TOKEN数量来输入，如有节省TOKEN考虑，可以设小。TOKEN数量可以查阅相关文档
    maxInputTokens: 6000
  ollama:
    model: qwen:latest
    apiKey:
    baseUrl: http://localhost:11434
    # 同上
    maxInputTokens: 6000
  openai:
    model: gpt-3.5-turbo
    apiKey: sk-xxxxxxxxxxxxxxxxxxx
    baseUrl: https://api.chatanywhere.com.cn
    # 同上
    maxInputTokens: 6000
# 选择使用的AI接口
useAi: openai
git:
  # 不会空则以此username为准，防止误领别人的工作
  # 为空字符串则自动获取
  username:
  repo:
    # [数组]
    # 自动遍历目录下的所有git仓库
    # 可以填项目集中的目录: C:\Web
    # 也可以填具体仓库目录: C:\Web\niubiGame
    - C:\Web
report:
  # 报告模式
  # [normal 详细叙述] [simple 简单概要]
  mode: normal
  # 间隔多少天汇报一次，默认一天报告一次
  # 1=只含今天，2=今天和昨天
  intervalDay: 1
  # 输出模式
  # file 输出文本文件
  # print 打印到终端
  out: print
  # 报告语言 [chs|en]
  lang: chs
  # 是否开启AI-FLOW以提高报告精准度 (会额外消耗小部分TOKEN和时间)
  flow: true
